### ISSUE TITLE
这里有个小问题

### ISSUE THREAD

**Issue by leqq00** [xuepengdong/phalapiredis#1]
![image](https://github.com/xuepengdong/phalapiredis/assets/35185509/8ce88feb-af19-4c76-a52b-2fe0a373ca46)

**Comment by xuepengdong** [comment]
麻烦详细说一下，我处理一下。

**Comment by leqq00** [comment]
DI()->redis->get_time($hex, 0)  这样指定0库的时候没有指定上去， 缓存被写在了1库

**Comment by leqq00** [comment]
$arr = \PhalApi\DI()->config->get('app.redis.DB');
        if(is_int($name)){
            $db = $name;
        }else{
            $db = isset($arr[$name]) ? $arr[$name] : 0;
        }
        if($this->db_old != $db){
            $this->redis->select($db);
            $this->db_old = $db;
        }
        用户的配置不一定放在app配置文件下面， 建议使用初始化传进来的配置

**Comment by xuepengdong** [comment]
> DI()->redis->get_time($hex, 0) 这样指定0库的时候没有指定上去，缓存被写在了1库

\PhalApi\DI()->redis->set_time('test', 'test', 86400, 0);    是写在0库的，你自己测试一下。 get_time是获取，set_time是设置

**Comment by xuepengdong** [comment]
> $arr = \PhalApi\DI()->config->get('app.redis.DB'); if(is_int($name)){ $db = $name; }其他{ $db = isset($arr[$name]) ? $arr[$name] : 0; } if($this->db_old != $db){ $this->redis->select($db); $this->db_old = $db; } 用户的配置不一定放在app配置文件下面，建议使用初始化传进来的配置

\PhalApi\DI()->redis->set_time('test', 'test', 86400); 这样不设置数据库会默认存储在0库中
